name: Scala
on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        java:
          - jdk15
    steps:
      - uses: actions/checkout@v2.3.2

      - name: "Cache for sbt & coursier ♨️"
        uses: coursier/cache-action@v4.1

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v12

      - name: "Install Cachix ❄️"
        uses: cachix/cachix-action@v8

      - name: "Run with ${{ matrix.java }} 🚀"
        run: nix-shell --argstr java "${{ matrix.java }}" --run "sbt ++ 'test;mdoc'"
