name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: olafurpg/setup-scala@v5

    - name: Cache Coursier dependencies
      uses: actions/cache@v1
      with:
       path: ~/.cache/coursier
       key: ${{ runner.os }}-${{ github.ref }}
       restore-keys: |
        ${{ runner.os }}-${{ github.ref }}

    - name: Cache Ivy dependencies
      uses: actions/cache@v1
      with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-${{ github.ref }}
        restore-keys: |
         ${{ runner.os }}-${{ github.ref }}

    - name: Tests
      run: sbt -J-Xms4G -J-Xmx4G fullBuild
